CREATE TABLE topicos (
  id BIGINT NOT NULL AUTO_INCREMENT,
  autor VARCHAR(255) NOT NULL,
  curso VARCHAR(255) NOT NULL,
  estatus VARCHAR(255) NOT NULL,
  fecha_creacion DATETIME(6) DEFAULT NULL,
  mensaje TEXT NOT NULL,
  titulo VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;